### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by mikemfleming** [galenmaly/lighterpack#102]
I'm a JavaScript dev that is also a UL hiker and have benefitted from using Lighterpack and would like to pay back a little. Perhaps some of the issues on here could be labeled 'good first contribution' so I'd know where to start without stepping on any toes?

Thanks!

edit: a contributing guide would be nice also. Just something to document the git workflow and review process if any. 🤓

**Comment by tinydinosaurs** [comment]
Hi! I totally agree with the above comment. Also "beginner" and "bug" labels at would be awesome! It's been a long time since I contributed to a non-work-related project, and this is definitely where I'd like to start.

**Comment by galenmaly** [comment]
Very belated contributing doc! It's barebones now given the state of the project, but will be expanded on as we move towards more feature work.

https://github.com/galenmaly/lighterpack/blob/master/CONTRIBUTING.md
