### ISSUE TITLE
Calories Field

### ISSUE THREAD

**Issue by amokrunner** [galenmaly/lighterpack#106]
Thoughts on a calories field?
It could be implemented similarly to price, but it wouldn't be applicable to most items so maybe thats not best. 
Possibly it could be tied to consumables, where if you mark something as consumable there is an additional field or modal input for calories, and then in the pack summary there is just another number for calories to the right of the consumables weight.

**Comment by johnabela** [comment]
Not sure about this one, seems like it might be pushing the boundaries of the POU of lighterpack.

**Comment by amokrunner** [comment]
Possibly. Either way, I should close this issue as a duplicate of issue #12.
