### ISSUE TITLE
Security Issue - Information Disclosure

### ISSUE THREAD

**Issue by Az0res** [galenmaly/lighterpack#109]
Hello,

Apparently, Google automatically crawls all the pages of the online version of the tool. Thus, if you create a list and don't want to share it, it is still possible to find it on Google. 

####Reproduction steps:

  * Create a list, and don't share it. 
  * Copy and paste the sharing URL in Google (you might need some time for Google to index it)
  * Boum, you have access to info that was not shared.

####Mitigation:

Have a valid robots.txt and maybe .htaccess?

**Comment by galenmaly** [comment]
Thanks for sharing this issue. I'm not sure I quite understand it though - it'd be helpful for me if you could elaborate on steps 2 and 3 in your repro steps.

Step 2: Just to clarify, by "sharing URL" you mean a URL like https://lighterpack.com/r/16jtk0 ?

Step 3:  What "info" is now accessible? Is it the contents of the list? Or is it more?

On the surface this sounds like it is working as intended and there is no security issue. In the repro steps you are **literally** sharing the list when you paste the URL into Google, and so it becoming accessible is expected. I look forward to hearing if there's something I'm missing though.
