### ISSUE TITLE
Vue: data compatibility issues

### ISSUE THREAD

**Issue by galenmaly** [galenmaly/lighterpack#125]
This is a major blocker for launch of the Vue branch.

The data structure lighterpack uses has never had rigorous enforcement, and as a result some people have bad data that the old LighterPack mostly works with. The Vue branch tries a *tiny* bit more to care about the data format and therefore refuses to load some peoples data.

**We need to be confident that people will still be able to load their list as normal after  launching the rewrite**

There are a number of things that can be done here. A few options include:

1. Writing a diagnostic tool to load a library in the old codebase and the new codebase and make sure they're the same.
2. Write a one-time script to fix up people's data in the DB
3. Write some server side code to enforce data structure when sending down over-the-wire, and again on saving.

Would love to hear other thoughts here too!

**Comment by crsmyz** [comment]
I'll add to that and concur with the 3rd option too, but add that we can enforce it using JOI validation and/or data base schemas from something like mongoose. The implementation is up for debate but the important part is some sort of data validation keeping everything consistent across the board.

**Comment by colinmxs** [comment]
Adding server-side validation doesn't really solve the problem of dealing with legacy data, and forcing users to manually correct their data would be maddening, IMO. 

If we can transform as much malformed data as possible into a known format, we can add server-side validation and unit tests later to prevent regressions.

@galenmaly how big is the library database? I bet we could scan the documents and compile a list of unique data models.

**Comment by galenmaly** [comment]
Right, while #3 is most certainly the solution in the long-term, the issue at hand is dealing with the transition while keeping in mind that user experience is paramount. If we're going to introduce a jarring UX we should be informed about how many users are impacted and how much work they'd need to do, etc, and do our best to autofix as much as possible.

@crsmyz - FYI if this impacts technology decisions, I'd like to potentially move away from Mongo towards (probably) Postgres in the near future. Happy to discuss that further in chat or a separate thread!

@colinmxs - The DB appears to be a few GB depending on which Mongo statistic you listen to. Would love to run any script you come up with to help with diagnosing this!

**Comment by darrikmazey** [comment]
i would think looking at what the Vue branch cares about more than master and then seeing how master deals with that data, we could apply an as-needed fix to Vue such that when it encounters that malformed data it "works with it" the way master used to and saves it normalized.  then data could be eventually normalized without user intervention.  the "Third Option" could be applied as a gatekeeper on storage for new data.

**Comment by darrikmazey** [comment]
and for the record, i manage a handful of postgres clusters for work, handling about 3k reads/s and 1500 writes/s.  i highly second a move to posgres over mongodb and would participate in that discussion and discuss migration possibilities.

**Comment by vtrhyno** [comment]
What @darrikmazey said.  Mongo's fine for quick development, but if you want a stable data model something like postgres is a better idea. (Data warehousing consultant)

**Comment by galenmaly** [comment]
Fixed for now  by https://github.com/galenmaly/lighterpack/commit/6a44d531bc502842a73c1de1829e83a09968cd39

The inconsistencies will be fixed when the library is loaded. This particular fix doesn't prevent future inconsistencies from reappearing, some sort of additional validation should be put in place for that.
