### ISSUE TITLE
Vue: The share page doesn't show prices in the totals box

### ISSUE THREAD

**Issue by galenmaly** [galenmaly/lighterpack#134]
This is also a problem in the current version of LighterPack - but it's a pretty bad miss. Okay to fix for Vue release.

**Comment by crsmyz** [comment]
This should be gtg, I'll check back later for comments on the PR or any small improvements.
https://github.com/galenmaly/lighterpack/pull/140

**Comment by galenmaly** [comment]
Fixed by @crsmyz!
