### ISSUE TITLE
[Bug] Dragging Worn Items to new list from Gear Column (Firefox Specific)

### ISSUE THREAD

**Issue by Zorks** [galenmaly/lighterpack#143]
Replication: 
1. Open lighterpack.com in Firefox
2. Create an item for one backpacking list (and thus is in the master gear column) and mark it as worn
3. Create a new backpacking list and drag item into it

Result:
The item will have the "worn" icon highlighted in the new list as well, but will not be counted towards worn weight until the worn icon has been clicked once. The icon highlight will not be changed with first click but will accurate reflect the worn weight. The second click will deactivate the worn icon and remove it from worn weight, and the third click will reactivate the icon and add it back to worn weight. 

Screenshot shows example where various worn items have been dragged to a new list but only one (the hat) has been clicked:
![lighterpack_bug](https://user-images.githubusercontent.com/6314048/62636339-35738080-b8ee-11e9-8412-63ee5b7d39d7.jpg)

Notes:
This was observed using Firefox Quantum 68.0.1 (64-bit).
Chrome Version 75 (64-bit) does not exhibit this behavior and the items do not reflect being worn when initially dragged into a new list. 
In Firefox, a refresh of the page will accurately show the recently dragged items as not worn (unless they've been manually selected again) which makes me suspect this is a caching issue of some sort. 

Given the fix is a simple F5 reload, this is a low priority bug but I thought I should bring it to your attention at least. 

Edit: The same behavior can be seen with the consumable icon as well
2nd Edit: amounts exhibit the same behavior, showing the old amount from previous list when added to a new list until refresh.

**Comment by galenmaly** [comment]
Thanks for reporting this bug! It was fixed in the Vue rewrite which launched yesterday, please let me know if you see it again.
