### ISSUE TITLE
Total worn weight error

### ISSUE THREAD

**Issue by tie-dyed-sox** [galenmaly/lighterpack#153]
Increasing the quantity of an item marked as worn weight causes the total weight to increase, but it does not affect the reported total worn weight.

**Comment by Zorks** [comment]
I'm not seeing this while using Firefox 70.0.1 on desktop, both worn weight and total weight increases/decreases with quantity adjustments. What platform are you seeing this on?

**Comment by tie-dyed-sox** [comment]
Same here - Firefox 70.0.1 on desktop. I created a new list, added a new item, set its weight to 100g, set quantity to 2, and marked it as worn. Total weight is 200g, but total worn weight is only 100g. I'd expect it to be 200g as well.

**Comment by Zorks** [comment]
Oh, I see what you're doing; I was testing changing from qty 0 to qty 1 and back again. 

I am admittedly not a contributor to this project, but from what I understand the functionality you're seeing is expected, if not documented well.  2nd (and 3rd, and 4th, etc) copies of items aren't expected to be worn together and thus don't affect worn weight. 

This has the advantage of allowing you to just have one entry for clothing (underwear for example) with a qty of 2+ but only having one marked as worn and the spares marked as pack weight. The downside is trekking poles (and socks) do need to be weighted as a pair, if that's how you "wear" them.

**Comment by tie-dyed-sox** [comment]
Ah, I was beginning to suspect that the behaviour was by design. Thanks for your response.
