### ISSUE TITLE
Quantity Box Too Small

### ISSUE THREAD

**Issue by cazzamatazz** [galenmaly/lighterpack#2]
I use a value of "0.5" in the qty box in order to indicate that a piece of equipment is shared gear (i.e. I'm carrying half the weight).

This doesn't show up nicely
![](https://cloud.githubusercontent.com/assets/8031988/3438169/5a32b5f2-00c1-11e4-990e-305a1c72559a.PNG)

Once you leave the page, it is not remembered. When i come back it is changed to a "0".
![](https://cloud.githubusercontent.com/assets/8031988/3438206/5c4638c2-00c2-11e4-993e-e484c59633e5.PNG)

Any ideas?

**Comment by galenmaly** [comment]
possibly has fixed this.
