### ISSUE TITLE
Enhancement - add comment/subtitle blocks for title and category headers

### ISSUE THREAD

**Issue by dullroar** [galenmaly/lighterpack#21]
Just like the individual items get comment fields for a bit of explication, I would like to see a comment block under the title (something about 4 lines long, say), and a one-line block next to or under each category heading. Since I am using my list not just to track for myself but to communicate to others, it would be helpful to explain the trip/packing list and category choices better. Not a big deal, but a "nice to have."

**Comment by galenmaly** [comment]
I've added a list description section. It can be enabled through the new settings dropdown, and markdown is supported. 

I haven't added category descriptions as displaying them in an elegant matter would be a harder problem to solve - I'd recommend just using the list description field for everything.

**Comment by johnabela** [comment]
Hey, I like this!

I had been creating a section called "Resources" and just adding links to my posts/videos in that manner, but this list description is nicer.

![000](https://cloud.githubusercontent.com/assets/3039327/19024232/d9b6b766-88b3-11e6-8bb3-a1996570022c.JPG)

I am not sure if it would look better or not, but did you happen to try adding some text above the list description section, entitled "Description" _(or some such)_ to help make it stand out, or rather look more in line with the rest of the design?

**Comment by galenmaly** [comment]
Good call, I've added a title to the section.

**Comment by dullroar** [comment]
Thanks for adding this!
