### ISSUE TITLE
imgur upload failes for me

### ISSUE THREAD

**Issue by sachbearbeiter** [galenmaly/lighterpack#232]
Are there any other people?

**Comment by sachbearbeiter** [comment]
"app.ddb859ffe7fe6f7eaa47.js:2     POST https://lighterpack.com/imageUpload 500 (Internal Server Error)"

**Comment by rogermbyrne** [comment]
i sent an email a few days ago, no reply.

**Comment by galenmaly** [comment]
The imgur API is returning a 500, but https://status.imgur.com/ claims there aren't any problems.

I was hoping they'd get it sorted on their end, but it looks like I might need to look into a new image hosting solution. I'll have time to look into it later this week.

**Comment by m-finn** [comment]
> Are there any other people?

Same here

**Comment by mike-burns** [comment]
I know basically nothing, but when I compare the imgur docs to the code, they look different.

Docs: https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139
Code: https://github.com/galenmaly/lighterpack/blob/908033af3aa0f55ecdfd03472e8acdcadfe0e124/server/endpoints.js#L393

From the docs I'd expect something closer to this:

```javascript
const formData = {
  image: files.image,
  type: "file"
};
request.post({
    uri: 'https://api.imgur.com/3/image',
    headers: { Authorization: `Client-ID ${config.get('imgurClientID')}` },
    formData: formData,
    json: true
}, (e, r, body) => {
  // ...
});
```

... but like I said, I know basically nothing and maybe I'm misinterpreting the docs.

---

I'm always on the other side of the API equation, and at some point if a API client sends me data that is so far from what I expect, it's going to end up as a 500. Input validation can only get you so far. Not sure whether that's what is happening here.

**Comment by galenmaly** [comment]
This should be fixed. It looks like imgur removed support for the way we had been uploading images for the last 10 years.

https://github.com/galenmaly/lighterpack/commit/32ab8baa0110b75b6b1bd6f9017f51960334388e?diff=split&w=1
