### ISSUE TITLE
Image upload failing

### ISSUE THREAD

**Issue by rogermbyrne** [galenmaly/lighterpack#233]
same error as before? Upload failed! If this issue persists please file a bug.

**Comment by cizekmilan** [comment]
I have the same problem. Tested in MS Edge and Mozilla firefox (latest versions).

**Comment by nuzicx** [comment]
Same Problem, across all lists and all items

**Comment by m-finn** [comment]
Same problem for me too. Is this repo maintained? Seems to be quite out of date.

**Comment by janbanan007** [comment]
Still failing when uploading image.

**Comment by sachbearbeiter** [comment]
Same problem ... Btw.: Are there not a few JS developers who would continue this project as a community project (or as a fork)? As a designer, I would be happy to invest a few hours on a regular basis.

**Comment by rogermbyrne** [comment]
seems to be Resolved. closing

**Comment by m-finn** [comment]
This is re-occurring for me today
