### ISSUE TITLE
Allow attaching a price to each item

### ISSUE THREAD

**Issue by DavidChenware** [galenmaly/lighterpack#27]
Allow each item to attach a price to the item, in addition to the existing worn status, food status, image, link, and star status.

Use case: Accumulating specific gear sets to recommend to people in specific price ranges, making people cry over how much their pack costs, help people budget for specific gear sets.

e.g. /r/campingandhiking or /r/wildernessbackpacking, "Here is our beginner backpacking recommended list in this budget range for this type of person" or something of the sort. It would make it sooooooooo easy for people that are beginners or looking to move in to different gear type groups to just say "hey go buy this stuff and you won't die and maybe have some fun too".

**Comment by bobbymarko** [comment]
I was wishing for something like this in addition to 'buy now' links. They could be affiliate links to help raise some money to pay for hosting/development.

**Comment by dgirgenti** [comment]
Can't you just put the price in the item description?

**Comment by DavidChenware** [comment]
That leaves out sorting, cool charts, totals, I'm probably missing something.

**Comment by oddalot** [comment]
Yah. Love the app, but this feature would surely make it even better!

**Comment by possibly** [comment]
https://github.com/galenmaly/lighterpack/pull/36 may resolve this.

**Comment by galenmaly** [comment]
The initial version of item prices has now been released, thanks to martinzirkle. You can turn on item prices through the new "settings" dropdown at the top. 

Future enhancements that would be nice, as per discussion in this thread:
1) subtotals/charts for price (in the subtotals section where it says "weight" should be conditionally turned into a dropdown to change to price)
2) sorting - should come with a general purpose sorting enhancement

**Comment by johnabela** [comment]
I just tested this, and the values are not being saved. As soon as you click on another list on the left panel, than go back to the previous list where you added the prices, all the values are at 0.

**Comment by galenmaly** [comment]
Looks like there's an issue with it not working on brand new lists. Looking into it.

**Comment by galenmaly** [comment]
I've deployed a fix for this -  refresh your page to get the fix. The issue was only affecting newly created items which is why it wasn't caught.

**Comment by johnabela** [comment]
confirmed resolution

**Comment by johnabela** [comment]
uggh... a [bit over $2100 bucks](https://cdn3.patreon.com/1/patreon.posts/3553775438218381989.jpg?v=fmrgwWXPdsb0-W4yudKCpRtSLa6dhIZ0D_nbwGtqPKE%3D) for my sub 4 pound bpw setup. ([video](https://www.youtube.com/watch?v=1sBPXCwcZf4))

[https://lighterpack.com/r/gbzu21](https://lighterpack.com/r/gbzu21)

Thanks for adding this feature guys.

**Comment by DavidChenware** [comment]
Excellent progress, thank you.
