### ISSUE TITLE
Saved items marked as consumable don't retain their calculations in the calculation pie chart area

### ISSUE THREAD

**Issue by DavidChenware** [galenmaly/lighterpack#28]
1. Have List A with an Item A marked as consumable
2. Create List B
3. Add Item A to List B
4. See that the pack weight on List B DOES add the item weight from the consumable item.

**Comment by galenmaly** [comment]
Thanks for reporting this bug. This was caused by a display bug in that the item wasn't actually marked as consumable. This has been fixed, please let me know if you see it again.
