### ISSUE TITLE
Allow URL for picture

### ISSUE THREAD

**Issue by zbeekman** [galenmaly/lighterpack#29]
It would be great to allow a URL for the item picture rather than having to upload it...

**Comment by zbeekman** [comment]
ping @galenmaly

**Comment by gpanders** [comment]
I just submitted PR #48 which addresses this. @galenmaly just needs to modify the sprites image file to add an "Use an image from the web" icon and then it's ready to go.

**Comment by galenmaly** [comment]
This is deployed now
