### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by benklocek** [galenmaly/lighterpack#30]
Allow for disabling items, so you can add multiple sleeping bags for instance, and only enable the one you plan on bringing.

**Comment by pistonrod8** [comment]
If you click the "X" at the right of the item, it will be removed from your active list and be available in your Gear list on the left. You can then drag another item into your active list.

**Comment by galenmaly** [comment]
A workaround for this is to set the quantity of this to zero. I'm not planning on adding this feature right now as it would clutter the UI too much.

When we get columns that can be customized on a per-user basis I'd love to add this feature in.
