### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by pistonrod8** [galenmaly/lighterpack#32]
What you call Pack Weight, the rest of the community calls Base Weight. Base Weight is the weight of everything minus consumables and worn items as you have it.

Total Pack Weight should be included, too, as it gives you the weight of your pack at the start of your trek. Total Pack weight is base weight plus consumables, i.e. the weight of your pack at the trail head. I find myself constantly adding Pack Weight and Consumables together to get this important number.

You have created a great tool, and I very much appreciate the work that has gone into it.

**Comment by galenmaly** [comment]
I've renamed pack weight -> base weight.

As for total pack weight, I'm reluctant to add more rows to that part of the page right now - it's already rather cluttered and is not too hard to calculate. If this is something others want please chime in and I'll reconsider (something like a hover over with more details?)

**Comment by pistonrod8** [comment]
Great. Thanks. I'll continue to calculate.

Maybe a way to keep it clutter-free would make Base Weight/Pack Weight selectable from a drop-down menu. The user can decide what he wants to see at that point.
