### ISSUE TITLE
'Share Your List' link goes to someone else's gear list

### ISSUE THREAD

**Issue by DarkStarX1** [galenmaly/lighterpack#35]
This has never been an issue before. If I go to the share link provided by the app, it takes me to someone else's gear list. 

Just in case this helps, here's what I did today when I encountered the issue: I duplicated an existing gear list of mine using 'Copy a List' and made several edits to it. The share link provided for this new list goes to someone else's list.

**Comment by DarkStarX1** [comment]
I just noticed that the last three lists I've created, which were created 1-2 weeks ago, all have the same share link that goes to someone else's list, so this bug could have occured before the last push.

**Comment by galenmaly** [comment]
Thanks for noticing this. Looks like the deployment last night broke some things.

I've fixed it so new lists going forward will get unique IDs properly. Going back now to fix the ones with duplicate IDs

**Comment by DarkStarX1** [comment]
No problem. Thanks for the great app!

**Comment by galenmaly** [comment]
I've given new Ids to all of the lists duplicate Ids and forced a logout of the 14 users affected to make sure no old data would be cached. Please let me know if anyone runs into any issues.
