### ISSUE TITLE
[Feature Request] Duplicate List

### ISSUE THREAD

**Issue by johnabela** [galenmaly/lighterpack#37]
Sorry if this has already been requested before, did a quick search and did not see it.

I think my #1 request would be a 'duplicate list' feature/link.

The vast majority of my lists are almost the same, with just a couple of pieces of gear that change dependant upon the hike.

Not having to build a new gear list from the ground up, when an almost identical one already exists, gets kind of old.

**Comment by galenmaly** [comment]
This feature exists - just hover over the "Add new list" link and the "copy a list" feature is there in the dropdown.

One issue is that tablet users can't access this, but the site isn't tablet-optimized at all right now so that's a separate task.

**Comment by johnabela** [comment]
{insert the}  "_oh bloody hell_" comment here
