### ISSUE TITLE
Document how to self-host

### ISSUE THREAD

**Issue by mrvdb** [galenmaly/lighterpack#38]
Unless I've missed it, some information on how to self host would be nice, such as:

- mention the format and config of the needed config.js file
- what is the file extIds.txt  which seems to be needed
- for images, a imgur account seems to be needed, a few notes on that would be nice 

After I found these 3 things I got the basic system running locally now. 

I'm trying to migrate from geargrams and want to patch the csv import so it can read my csv file.

**Comment by galenmaly** [comment]
You're fast! Up until yesterday these files were checked in to the repository but I had to remove them because they were causing too much headache when deploying.

I've created a wiki page with samples of those files and updated the install instructions in the README.
