### ISSUE TITLE
Vagrant setup instructions are not complete

### ISSUE THREAD

**Issue by andyholton** [galenmaly/lighterpack#41]
The instructions for getting lighterpack up and running with Vagrant are not quite complete, and there are some steps that differ from the normal instructions. The steps I took were:

Running with Vagrant
-----------
1. Install Vagrant and VirtualBox
2. Download Vagrantfile and node-bootstrap.sh from vagrant folder to a folder on your local machine
3. Run ```$ vagrant up``` in the folder where you downloaded the two files.
4. Create a config.js and extIds.txt in /var/www/lighterpack based on the wiki: https://github.com/galenmaly/lighterpack/wiki/Config-files
5. Install dependencies ```$ sudo npm install```
6. Start app ```$ nodejs app.js```

I think for someone familiar with the environment, the current instructions are clear enough, but it took me a while to get things up and running.

**Comment by galenmaly** [comment]
Thanks! I've put your updated the instructions in the readme.
