### ISSUE TITLE
Enhancement: An item library

### ISSUE THREAD

**Issue by hikingnerd** [galenmaly/lighterpack#50]
What if every item you manually input was added to your personal item library, so you never have to reweigh or look up previous lists?

**Comment by johnabela** [comment]
Do you mean a drag-and-drop from the gear list on the left plane into a category list on the right plane?

**Comment by hikingnerd** [comment]
That's it. I guess it's time to say goodbye to my spreadsheet and use
lighterpack for everything now...

**Comment by kurtabersold** [comment]
So, should this still be an open issue?

**Comment by hikingnerd** [comment]
Sorry I think it should be closed. False issue.
