### ISSUE TITLE
Enhancement: Gear Sort

### ISSUE THREAD

**Issue by ghost** [galenmaly/lighterpack#52]
I find myself sorting gear based on weight quite often. Would be nice to have some sorting tools for each category. Sort by Name, Weight, Price, etc.

**Comment by johnabela** [comment]
Guessing you mean on the left plane. Yeah, right now all we can do is drag and drop. I keep them sorted by alpha (which for me is company name) but agree a small link/action-div right below the 'search' box would be nice.

**Comment by DarkStarX1** [comment]
That would be nice, but I'm talking about for each category in the right pane. Often I like to see the category items listed from highest to lowest weight.

**Comment by kurtabersold** [comment]
Correct me if I'm wrong, but this sounds like a duplicate of #11.

**Comment by galenmaly** [comment]
This feature is high on my priority list, but closing as it's a duplicate of #11
