### ISSUE TITLE
Rewrite LighterPack in Vue

### ISSUE THREAD

**Issue by galenmaly** [galenmaly/lighterpack#59]
The current jQuery setup seems like it's pretty daunting to approach and is rather error prone. 

Rewrite the site in Vue.

**Comment by galenmaly** [comment]
I made this issue to track any bugs anyone finds in the rewrite (Vue branch, hosted @ https://beta.lighterpack.com/) - if all goes well I'll plan on merging to master and launching the site in a few days.

**Comment by amokrunner** [comment]
Hi Galen. Are you still planning on launching this vue rewrite?

**Comment by galenmaly** [comment]
Yes - the master branch can be considered frozen.
