### ISSUE TITLE
Enhancement: Number formatting after entry

### ISSUE THREAD

**Issue by fortchagos** [galenmaly/lighterpack#60]
Dollar value allows entries with more than two cent digits.  It would be a nicer display to round to two decimal points.

Weights less than 1.0 do not show a leading zero.  Recommend automatically formatting entries display leading zero when not entered (e.g. ".8" becomes "0.8").

Note the above happen when entering numbers (hitting return or the box losing focus could trigger automatically formatting the entry).

**Comment by fortchagos** [comment]
Note the above only seems to happen during entry.

**Comment by galenmaly** [comment]
Leading zeros and rouding to 2 decimals places were added in the Vue rewrite - let me know if you have any issues with it!
