### ISSUE TITLE
Enhancement: Checkboxes to optionally include/exclude Consumables, Worn, and Base in the pie chart.

### ISSUE THREAD

**Issue by fortchagos** [galenmaly/lighterpack#62]
I like how you can drill down on a category and see the pie chart for items in that category.

A nice complement would be to have check boxes next to the Consumable, Worn, and Base totals to exclude those categories from the pie chart (e.g. click on Consumable check box to see how Worn and Base are distributed.  Click on Consumable and Worn to see how Base is distributed.

**Comment by johnabela** [comment]
Seems like this is just too much of a micro feature to make it into production.

**Comment by galenmaly** [comment]
While this would be nice in theory,  coming up with an elegant ui would be necessary first.  On top of that,  there simply are so many higher priority items. Closing for now,  if we get to the point in the future where all other high priority items are taken care of then we can reconsider.
