### ISSUE TITLE
Enhancement: Add a Pack Weight total

### ISSUE THREAD

**Issue by fortchagos** [galenmaly/lighterpack#64]
The current Total Weight summary includes all three of Base, Consumables, and Worn.  It would be most convenient to also have a Pack Weight total providing the weight one actually carries in their pack.

Pack Weight = Base Weight + Consumables Weight
Total Weight = Base Weight + Consumables Weight + Worn Weight

Until I realized Worn was included in the Total Weight, I kept thinking my pack seemed a little heavy.  :)

![packweight](https://cloud.githubusercontent.com/assets/25619764/25983644/15a52970-36b4-11e7-9913-80f055040e4e.png)

Note the shared page should have the popups over the worn and consumable icons changed to read "... and not included in base weight."

![wornpopup](https://cloud.githubusercontent.com/assets/25619764/26013405/35961600-3726-11e7-8e89-fa668f765202.png)

**Comment by johnabela** [comment]
Been wondering when somebody would bring this up.

So we basically have four terms/standards with four basic clauses:

**BPW** - Base Pack Weight - _backpack + everything in/on backpack, but not consumables nor garments/shoes being worn_

**TPW** - Total Pack Weight - _BPW + consumables_

**TBW** - Total Base Weight - _BPW + garments/shoes worn, but not consumables_

**FSO** - Full Skin Out - _all gear, garments, consumables_

Of these, the BPW and TPW are the two most used values. It is rare that somebody talks about their TBW, even though it should be talked about a lot more. FSO is of course, the one we all like to hide the truth about :-D

So yeah, I am totally up for this suggested enhancement, it is a data value that needs to be highlighted more within the hiking community.

**Comment by galenmaly** [comment]
Unfortunately,  adding an additional row here is really going to clutter up the UI and add confusion for the casual viewer - the number of totals being shown right now is already too many.

I already have a change in the beta site to show this info on hover,  but i will not be adding it to the default display.
