### ISSUE TITLE
Option To Remove Header "Description"

### ISSUE THREAD

**Issue by johnabela** [galenmaly/lighterpack#84]
Hello,

Can we please have an option to remove the "Description" text _(and line under it)_ on the /r/ page.

I am currently working on my 2018 primary gearlist and have a picture at the top of the description text area and that stupid "Description" just makes the /r/ page look stupid.

Ref: [https://lighterpack.com/r/2dbk1c](https://lighterpack.com/r/2dbk1c)

**Comment by amokrunner** [comment]
Hi John. I have no opinion on this issue, but something you could do instead: 
Since you have your own site, you could create a page there exactly as you want it, remove the title and description from your lighterpack list, then use the "Embed your list" html code on that page.

**Comment by galenmaly** [comment]
I've made this change in the Vue branch - just removing the header, not an option to remove it.

**Comment by galenmaly** [comment]
Finally live!
