### ISSUE TITLE
Image height in list 

### ISSUE THREAD

**Issue by amokrunner** [galenmaly/lighterpack#86]
I think a maximum image display height would be good, maybe set at 3em or something like that, so images with portrait orientations don't use up so much vertical space in the list

**Comment by amokrunner** [comment]
I hadn't been using imgur, rather just adding URLs to images online from retailers/etc. I just tested imgur and it is cropping to a square at 90x90 pixels. Using URLs, there is no cropping done. Even with the cropping, I do think 90px is a little tall--maybe the max row height could be included as a customizable option under Settings.

Anyway, using URLs, attached are screenshots of it's current display and then the 2nd with the 4em max-height. 

Existing:
![screenshot1](https://user-images.githubusercontent.com/29108942/34326742-38b3be60-e869-11e7-98f3-fe40a14c1d05.png)

With 4em max-height
![screenshot2](https://user-images.githubusercontent.com/29108942/34326743-3b94fa36-e869-11e7-8312-c769c8a0a644.png)

**Comment by galenmaly** [comment]
Hmm, looks like `object-fit` doesn't have the support we need yet. Going to close this and we can find a different approach later.
