### ISSUE TITLE
Vue: sometimes changes aren't sticking

### ISSUE THREAD

**Issue by amokrunner** [galenmaly/lighterpack#88]
I am seeing an issue w/ the Vue code where sometimes the changes I make are not sticking. It appears to only happen when I have the same item in multiple lists. I've seen this happen now with weight and image fields.
If I have item X in list A and B, and I change the weight of X, it won't stick. If I remove it from B, then change it in A, then add it back to B, it's all good. 
Anybody else using the beta site experiencing the same?

**Comment by galenmaly** [comment]
This is handy. Saving bugs are the reason the Vue branch hasn't launched. I'll try and repro this when I get time next week.

**Comment by galenmaly** [comment]
Fixed in https://github.com/galenmaly/lighterpack/commit/4fe958749fe9c245ff7d50698b88bf3d12f146d1

Thanks again for the report!
