### ISSUE TITLE
embed in wordpress may not work

### ISSUE THREAD

**Issue by ryleyb** [galenmaly/lighterpack#9]
Depending on the WP setup, $ may not be assigned to jQuery, so to be certain, your embed code should be wrapped in something like this:

```
jQuery(function ($) {
	/* You can safely use $ in this code block to reference jQuery */
});
```

**Comment by robtown650** [comment]
Yes, mine isn't working due to this exact issue. I'm trying to find a workaround now.

**Comment by galenmaly** [comment]
I've changed the embed feature to work if "$" is taken by another library. It will also now work if jQuery is not present on the page. Thanks for reporting this issue!
