### ISSUE TITLE
Beta: move to production database? 

### ISSUE THREAD

**Issue by amokrunner** [galenmaly/lighterpack#94]
Can you update the beta site to use the production database? I'd like to spend more time on it to help find bugs but would like to keep all my content after its merged.

**Comment by galenmaly** [comment]
Done!

**Comment by amokrunner** [comment]
Thanks @galenmaly !
Just a warning for testers: switching back and forth between beta and production sites appeared to have corrupted my lists. Maybe I should have known that was a bad idea. Anyway, I was getting an error on login to the beta site ("An error occurred while loading your data"), but was still able to log into the production site. In the production site my lists were present but each category empty of items. From there I deleted all my lists and logged out. I was then able to log into the beta site again. Fortunately I had .csv's of everything. I'm going to stick to just the beta site for now.

**Comment by galenmaly** [comment]
Hey @amokrunner if you'd like your data restored from backup please email me @ info@lighterpack.com

**Comment by galenmaly** [comment]
I reverted beta back to the beta DB. Causing too many headaches for me - the data structures changed and so only beta.lighterpack.com can load the dataset after it makes a save.
