### ISSUE TITLE
saveLibrary XHR Makes Typing Very Slow

### ISSUE THREAD

**Issue by berney** [galenmaly/lighterpack#98]
Using https://lighterpack.com/ my browser will freeze while it does the XHR which makes typing really slow and painful. RTT is ~1.5s per request (per character).

Is it possible to do it asynchronously, so that the browser doesn't hang and you can type as fast as you want (the requests can sent immediately but the responses outstanding) , the saving will catch up when you stop typing? This will improve the UX.

Previously using lighterpack I never had this freezing slow typing problem. I'm not sure if it's due to a code change or something else.

**Comment by galenmaly** [comment]
Can you please provide some more details? Which field are you typing into that freezes your browser?

**Comment by berney** [comment]
The description field of an item. It probably happens on others as well.

**Comment by galenmaly** [comment]
I'm going to assume this problem is fixed in the Vue rewrite that launched yesterday. Please let me know if anyone continues to have this issue.
